services:
  multi-source-ai-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi-source-ai-agent
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL_NAME=${MODEL_NAME:-openai/gpt-oss-120b}
      - TEMPERATURE=${TEMPERATURE:-0.1}
      - MAX_TOKENS=${MAX_TOKENS:-2000}
    volumes:
      # Mount data directory for persistence
      - ./data:/app/data:ro
      # Mount logs directory
      - ./logs:/app/logs
    stdin_open: true
    tty: true
    networks:
      - ai-agent-network

  # Optional: Add a database container if needed for future expansion
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: ai-agent-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: ai_agent
  #     POSTGRES_USER: agent
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - ai-agent-network

networks:
  ai-agent-network:
    driver: bridge

volumes:
  # postgres_data:
  logs:
